-- =========================================
-- FOREIGN KEYS
-- =========================================

ALTER TABLE ai_conversations ADD CONSTRAINT ai_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE ai_conversations ADD CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE ai_feedback_logs ADD CONSTRAINT ai_feedback_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE ai_feedback_logs ADD CONSTRAINT ai_feedback_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE ai_price_estimates ADD CONSTRAINT ai_price_estimates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE carbon_reports ADD CONSTRAINT carbon_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE carbon_reports ADD CONSTRAINT carbon_reports_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE carbon_reports ADD CONSTRAINT carbon_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE client_access_tokens ADD CONSTRAINT client_access_tokens_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE client_access_tokens ADD CONSTRAINT client_access_tokens_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE companies ADD CONSTRAINT companies_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users (id);
ALTER TABLE company_email_domains ADD CONSTRAINT company_email_domains_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE company_email_domains ADD CONSTRAINT company_email_domains_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (auth_id);
ALTER TABLE cooperants ADD CONSTRAINT cooperants_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE customers ADD CONSTRAINT customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE customers ADD CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE customers ADD CONSTRAINT customers_company_fk FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE email_logs ADD CONSTRAINT email_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE email_logs ADD CONSTRAINT email_logs_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE email_queue ADD CONSTRAINT email_queue_recipient_user_id_fkey FOREIGN KEY (recipient_user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE email_queue ADD CONSTRAINT email_queue_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE energy_emissions ADD CONSTRAINT energy_emissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE entity_tags ADD CONSTRAINT entity_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;
ALTER TABLE external_operation_items ADD CONSTRAINT external_operation_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE external_operation_items ADD CONSTRAINT external_operation_items_external_operation_id_fkey FOREIGN KEY (external_operation_id) REFERENCES external_operations (id) ON DELETE CASCADE;
ALTER TABLE external_operations ADD CONSTRAINT external_operations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE external_operations ADD CONSTRAINT external_operations_received_by_fkey FOREIGN KEY (received_by) REFERENCES users (id);
ALTER TABLE external_operations ADD CONSTRAINT external_operations_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES users (id);
ALTER TABLE external_operations ADD CONSTRAINT external_operations_cooperant_id_fkey FOREIGN KEY (cooperant_id) REFERENCES cooperants (id) ON DELETE SET NULL;
ALTER TABLE files ADD CONSTRAINT files_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE files ADD CONSTRAINT files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE inventory ADD CONSTRAINT inventory_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE inventory ADD CONSTRAINT inventory_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE inventory_batches ADD CONSTRAINT inventory_batches_location_id_fkey FOREIGN KEY (location_id) REFERENCES inventory_locations (id) ON DELETE CASCADE;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users (id);
ALTER TABLE inventory_history ADD CONSTRAINT inventory_history_document_id_fkey FOREIGN KEY (document_id) REFERENCES warehouse_documents (id) ON DELETE CASCADE;
ALTER TABLE inventory_locations ADD CONSTRAINT inventory_locations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_location_id_fkey FOREIGN KEY (location_id) REFERENCES inventory_locations (id);
ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES inventory_batches (id);
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_item_id_fkey FOREIGN KEY (item_id) REFERENCES inventory (id) ON DELETE CASCADE;
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_reference_order_id_fkey FOREIGN KEY (reference_order_id) REFERENCES orders (id);
ALTER TABLE knowledge_categories ADD CONSTRAINT knowledge_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES knowledge_categories (id);
ALTER TABLE knowledge_categories ADD CONSTRAINT knowledge_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE knowledge_comments ADD CONSTRAINT knowledge_comments_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE knowledge_comments ADD CONSTRAINT knowledge_comments_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES knowledge_entries (id) ON DELETE CASCADE;
ALTER TABLE knowledge_entries ADD CONSTRAINT knowledge_entries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE knowledge_entries ADD CONSTRAINT knowledge_entries_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES machines (id) ON DELETE SET NULL;
ALTER TABLE knowledge_entries ADD CONSTRAINT knowledge_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE knowledge_entries ADD CONSTRAINT knowledge_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE knowledge_reactions ADD CONSTRAINT knowledge_reactions_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES knowledge_entries (id) ON DELETE CASCADE;
ALTER TABLE knowledge_reactions ADD CONSTRAINT knowledge_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE machines ADD CONSTRAINT machines_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE machines ADD CONSTRAINT machines_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE maintenance_logs ADD CONSTRAINT maintenance_logs_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES users (id);
ALTER TABLE maintenance_logs ADD CONSTRAINT maintenance_logs_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES machines (id) ON DELETE CASCADE;
ALTER TABLE maintenance_logs ADD CONSTRAINT maintenance_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE maintenance_logs ADD CONSTRAINT maintenance_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE maintenance_parts ADD CONSTRAINT maintenance_parts_maintenance_log_id_fkey FOREIGN KEY (maintenance_log_id) REFERENCES maintenance_logs (id) ON DELETE CASCADE;
ALTER TABLE maintenance_parts ADD CONSTRAINT maintenance_parts_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory (id);
ALTER TABLE material_emissions ADD CONSTRAINT material_emissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT notifications_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE operations ADD CONSTRAINT operations_assigned_operator_id_fkey FOREIGN KEY (assigned_operator_id) REFERENCES users (id);
ALTER TABLE operations ADD CONSTRAINT operations_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE CASCADE;
ALTER TABLE operations ADD CONSTRAINT operations_production_plan_id_fkey FOREIGN KEY (production_plan_id) REFERENCES production_plans (id) ON DELETE CASCADE;
ALTER TABLE operations ADD CONSTRAINT operations_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES machines (id);
ALTER TABLE order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE order_items ADD CONSTRAINT order_items_drawing_file_id_fkey FOREIGN KEY (drawing_file_id) REFERENCES files (id);
ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE orders ADD CONSTRAINT orders_linked_inventory_item_id_fkey FOREIGN KEY (linked_inventory_item_id) REFERENCES inventory (id);
ALTER TABLE orders ADD CONSTRAINT orders_assigned_operator_id_fkey FOREIGN KEY (assigned_operator_id) REFERENCES users (id);
ALTER TABLE orders ADD CONSTRAINT orders_drawing_file_id_fkey FOREIGN KEY (drawing_file_id) REFERENCES files (id);
ALTER TABLE orders ADD CONSTRAINT orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE orders ADD CONSTRAINT orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE production_plans ADD CONSTRAINT production_plans_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE production_plans ADD CONSTRAINT production_plans_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE CASCADE;
ALTER TABLE production_plans ADD CONSTRAINT production_plans_drawing_file_id_fkey FOREIGN KEY (drawing_file_id) REFERENCES files (id);
ALTER TABLE production_plans ADD CONSTRAINT production_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE production_plans ADD CONSTRAINT production_plans_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users (id);
ALTER TABLE production_plans ADD CONSTRAINT production_plans_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE products ADD CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE products ADD CONSTRAINT products_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE quality_control_items ADD CONSTRAINT quality_control_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES quality_control_plans (id) ON DELETE CASCADE;
ALTER TABLE quality_control_plans ADD CONSTRAINT quality_control_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE quality_control_plans ADD CONSTRAINT quality_control_plans_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE quality_measurements ADD CONSTRAINT quality_measurements_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES quality_control_plans (id) ON DELETE SET NULL;
ALTER TABLE quality_measurements ADD CONSTRAINT quality_measurements_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE quality_measurements ADD CONSTRAINT quality_measurements_measured_by_fkey FOREIGN KEY (measured_by) REFERENCES users (id);
ALTER TABLE quality_measurements ADD CONSTRAINT quality_measurements_item_id_fkey FOREIGN KEY (item_id) REFERENCES quality_control_items (id) ON DELETE CASCADE;
ALTER TABLE quality_measurements ADD CONSTRAINT quality_measurements_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE quality_reports ADD CONSTRAINT quality_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE quality_reports ADD CONSTRAINT quality_reports_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE quality_reports ADD CONSTRAINT quality_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE quality_reports ADD CONSTRAINT quality_reports_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users (id);
ALTER TABLE quality_reports ADD CONSTRAINT quality_reports_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES quality_control_plans (id) ON DELETE SET NULL;
ALTER TABLE quote_items ADD CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE;
ALTER TABLE quotes ADD CONSTRAINT quotes_converted_order_id_fkey FOREIGN KEY (converted_order_id) REFERENCES orders (id) ON DELETE SET NULL;
ALTER TABLE quotes ADD CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE quotes ADD CONSTRAINT quotes_company_fk FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE quotes ADD CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL;
ALTER TABLE quotes ADD CONSTRAINT quotes_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_permission_code_fkey FOREIGN KEY (permission_code) REFERENCES permission_definitions (code) ON DELETE CASCADE;
ALTER TABLE saved_filters ADD CONSTRAINT saved_filters_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE saved_filters ADD CONSTRAINT saved_filters_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE scheduled_reports ADD CONSTRAINT scheduled_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE tags ADD CONSTRAINT tags_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE time_logs ADD CONSTRAINT time_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE;
ALTER TABLE time_logs ADD CONSTRAINT time_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE time_logs ADD CONSTRAINT time_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES users (id);
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_permission_code_fkey FOREIGN KEY (permission_code) REFERENCES permission_definitions (code) ON DELETE CASCADE;
ALTER TABLE user_preferences ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE warehouse_document_items ADD CONSTRAINT warehouse_document_items_document_id_fkey FOREIGN KEY (document_id) REFERENCES warehouse_documents (id) ON DELETE CASCADE;
ALTER TABLE warehouse_document_items ADD CONSTRAINT warehouse_document_items_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES inventory (id);
ALTER TABLE warehouse_documents ADD CONSTRAINT warehouse_documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE warehouse_documents ADD CONSTRAINT warehouse_documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
