-- =========================================
-- DROP ALL RLS POLICIES IN TEST
-- =========================================
-- Uruchom to w TEST PRZED utworzeniem nowych policies
-- =========================================

DROP POLICY IF EXISTS "Service role full access on ai_conversations" ON public.ai_conversations;
DROP POLICY IF EXISTS "Users can create conversations" ON public.ai_conversations;
DROP POLICY IF EXISTS "Users can delete own conversations" ON public.ai_conversations;
DROP POLICY IF EXISTS "Users can update own conversations" ON public.ai_conversations;
DROP POLICY IF EXISTS "Users can view own conversations" ON public.ai_conversations;
DROP POLICY IF EXISTS "Service role full access" ON public.ai_feedback_logs;
DROP POLICY IF EXISTS "Users can insert own feedback" ON public.ai_feedback_logs;
DROP POLICY IF EXISTS "Users can view company feedback" ON public.ai_feedback_logs;
DROP POLICY IF EXISTS "Users can create estimates" ON public.ai_price_estimates;
DROP POLICY IF EXISTS "Users can view company estimates" ON public.ai_price_estimates;
DROP POLICY IF EXISTS "Admins can view audit logs" ON public.audit_logs;
DROP POLICY IF EXISTS "Only admins can manage blocked domains" ON public.blocked_email_domains;
DROP POLICY IF EXISTS "Public can read blocked domains" ON public.blocked_email_domains;
DROP POLICY IF EXISTS "Users can delete carbon_reports from their company" ON public.carbon_reports;
DROP POLICY IF EXISTS "Users can insert carbon_reports for their company" ON public.carbon_reports;
DROP POLICY IF EXISTS "Users can update carbon_reports from their company" ON public.carbon_reports;
DROP POLICY IF EXISTS "Users can view carbon_reports from their company" ON public.carbon_reports;
DROP POLICY IF EXISTS "Anyone can read with valid token" ON public.client_access_tokens;
DROP POLICY IF EXISTS "Users can create tokens for own company" ON public.client_access_tokens;
DROP POLICY IF EXISTS "Users can delete own company tokens" ON public.client_access_tokens;
DROP POLICY IF EXISTS "Users can update own company tokens" ON public.client_access_tokens;
DROP POLICY IF EXISTS "Users can view own company tokens" ON public.client_access_tokens;
DROP POLICY IF EXISTS "Owners can update their company" ON public.companies;
DROP POLICY IF EXISTS "Users can view their company" ON public.companies;
DROP POLICY IF EXISTS "Only admins can manage domains" ON public.company_email_domains;
DROP POLICY IF EXISTS "Public can read domains for registration" ON public.company_email_domains;
DROP POLICY IF EXISTS "Users can view their company domains" ON public.company_email_domains;
DROP POLICY IF EXISTS "Users can delete cooperants from their company" ON public.cooperants;
DROP POLICY IF EXISTS "Users can insert cooperants for their company" ON public.cooperants;
DROP POLICY IF EXISTS "Users can update cooperants from their company" ON public.cooperants;
DROP POLICY IF EXISTS "Users can view cooperants from their company" ON public.cooperants;
DROP POLICY IF EXISTS customers_delete_policy ON public.customers;
DROP POLICY IF EXISTS customers_insert_policy ON public.customers;
DROP POLICY IF EXISTS customers_select_policy ON public.customers;
DROP POLICY IF EXISTS customers_update_policy ON public.customers;
DROP POLICY IF EXISTS email_logs_insert_own_company ON public.email_logs;
DROP POLICY IF EXISTS email_logs_select_own_company ON public.email_logs;
DROP POLICY IF EXISTS email_queue_company_access ON public.email_queue;
DROP POLICY IF EXISTS "Users can insert energy emissions for their company" ON public.energy_emissions;
DROP POLICY IF EXISTS "Users can view global and company energy emissions" ON public.energy_emissions;
DROP POLICY IF EXISTS "Users can create entity tags" ON public.entity_tags;
DROP POLICY IF EXISTS "Users can delete entity tags" ON public.entity_tags;
DROP POLICY IF EXISTS "Users can manage entity tags" ON public.entity_tags;
DROP POLICY IF EXISTS "Users can view company entity tags" ON public.entity_tags;
DROP POLICY IF EXISTS "Users can view entity tags" ON public.entity_tags;
DROP POLICY IF EXISTS "Users can delete external_operation_items from their company" ON public.external_operation_items;
DROP POLICY IF EXISTS "Users can insert external_operation_items for their company" ON public.external_operation_items;
DROP POLICY IF EXISTS "Users can update external_operation_items from their company" ON public.external_operation_items;
DROP POLICY IF EXISTS "Users can view external_operation_items from their company" ON public.external_operation_items;
DROP POLICY IF EXISTS "Users can delete external_operations from their company" ON public.external_operations;
DROP POLICY IF EXISTS "Users can insert external_operations for their company" ON public.external_operations;
DROP POLICY IF EXISTS "Users can update external_operations from their company" ON public.external_operations;
DROP POLICY IF EXISTS "Users can view external_operations from their company" ON public.external_operations;
DROP POLICY IF EXISTS "Upload files" ON public.files;
DROP POLICY IF EXISTS "Users can delete own files" ON public.files;
DROP POLICY IF EXISTS "Users can upload files" ON public.files;
DROP POLICY IF EXISTS "Users can view company files" ON public.files;
DROP POLICY IF EXISTS "View company files" ON public.files;
DROP POLICY IF EXISTS "Only owners can delete inventory items" ON public.inventory;
DROP POLICY IF EXISTS "Users can create inventory items" ON public.inventory;
DROP POLICY IF EXISTS "Users can update their company's inventory" ON public.inventory;
DROP POLICY IF EXISTS "Users can view their company's inventory" ON public.inventory;
DROP POLICY IF EXISTS inventory_batches_company_isolation ON public.inventory_batches;
DROP POLICY IF EXISTS "Users can view their company's inventory history" ON public.inventory_history;
DROP POLICY IF EXISTS inventory_locations_company_isolation ON public.inventory_locations;
DROP POLICY IF EXISTS inventory_movements_company_isolation ON public.inventory_movements;
DROP POLICY IF EXISTS "Users can create transactions" ON public.inventory_transactions;
DROP POLICY IF EXISTS "Users can view their company's transactions" ON public.inventory_transactions;
DROP POLICY IF EXISTS "Admins can manage knowledge_categories" ON public.knowledge_categories;
DROP POLICY IF EXISTS "Users can view knowledge_categories from their company" ON public.knowledge_categories;
DROP POLICY IF EXISTS "Users can insert knowledge_comments" ON public.knowledge_comments;
DROP POLICY IF EXISTS "Users can view knowledge_comments from their company entries" ON public.knowledge_comments;
DROP POLICY IF EXISTS "Users can delete their own knowledge_entries" ON public.knowledge_entries;
DROP POLICY IF EXISTS "Users can insert knowledge_entries for their company" ON public.knowledge_entries;
DROP POLICY IF EXISTS "Users can update knowledge_entries from their company" ON public.knowledge_entries;
DROP POLICY IF EXISTS "Users can view knowledge_entries from their company" ON public.knowledge_entries;
DROP POLICY IF EXISTS "Users can delete their own reactions" ON public.knowledge_reactions;
DROP POLICY IF EXISTS "Users can insert their own reactions" ON public.knowledge_reactions;
DROP POLICY IF EXISTS "Users can view knowledge_reactions from their company" ON public.knowledge_reactions;
DROP POLICY IF EXISTS "Users can delete machines from their company" ON public.machines;
DROP POLICY IF EXISTS "Users can insert machines for their company" ON public.machines;
DROP POLICY IF EXISTS "Users can update machines from their company" ON public.machines;
DROP POLICY IF EXISTS "Users can view machines from their company" ON public.machines;
DROP POLICY IF EXISTS "Users can delete maintenance_logs from their company" ON public.maintenance_logs;
DROP POLICY IF EXISTS "Users can insert maintenance_logs for their company" ON public.maintenance_logs;
DROP POLICY IF EXISTS "Users can update maintenance_logs from their company" ON public.maintenance_logs;
DROP POLICY IF EXISTS "Users can view maintenance_logs from their company" ON public.maintenance_logs;
DROP POLICY IF EXISTS "Users can delete maintenance_parts from their company" ON public.maintenance_parts;
DROP POLICY IF EXISTS "Users can insert maintenance_parts for their company" ON public.maintenance_parts;
DROP POLICY IF EXISTS "Users can update maintenance_parts from their company" ON public.maintenance_parts;
DROP POLICY IF EXISTS "Users can view maintenance_parts from their company" ON public.maintenance_parts;
DROP POLICY IF EXISTS "Users can insert material emissions for their company" ON public.material_emissions;
DROP POLICY IF EXISTS "Users can update material emissions from their company" ON public.material_emissions;
DROP POLICY IF EXISTS "Users can view global and company material emissions" ON public.material_emissions;
DROP POLICY IF EXISTS "Users can update their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can view their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Users can delete operations from their company" ON public.operations;
DROP POLICY IF EXISTS "Users can insert operations for their company" ON public.operations;
DROP POLICY IF EXISTS "Users can update operations from their company" ON public.operations;
DROP POLICY IF EXISTS "Users can view operations from their company" ON public.operations;
DROP POLICY IF EXISTS "Users can delete order items from their company" ON public.order_items;
DROP POLICY IF EXISTS "Users can insert order items for their company orders" ON public.order_items;
DROP POLICY IF EXISTS "Users can update order items from their company" ON public.order_items;
DROP POLICY IF EXISTS "Users can view order items from their company" ON public.order_items;
DROP POLICY IF EXISTS "Only owners can delete orders" ON public.orders;
DROP POLICY IF EXISTS "Users can create orders" ON public.orders;
DROP POLICY IF EXISTS "Users can update their company's orders" ON public.orders;
DROP POLICY IF EXISTS "Users can view their company's orders" ON public.orders;
DROP POLICY IF EXISTS "Anyone can view permission definitions" ON public.permission_definitions;
DROP POLICY IF EXISTS production_plans_company_isolation ON public.production_plans;
DROP POLICY IF EXISTS products_company_isolation ON public.products;
DROP POLICY IF EXISTS "Users can manage QC items" ON public.quality_control_items;
DROP POLICY IF EXISTS "Users can view QC items" ON public.quality_control_items;
DROP POLICY IF EXISTS "Users can create QC plans for own company" ON public.quality_control_plans;
DROP POLICY IF EXISTS "Users can delete own company QC plans" ON public.quality_control_plans;
DROP POLICY IF EXISTS "Users can update own company QC plans" ON public.quality_control_plans;
DROP POLICY IF EXISTS "Users can view own company QC plans" ON public.quality_control_plans;
DROP POLICY IF EXISTS "Users can create measurements for own company" ON public.quality_measurements;
DROP POLICY IF EXISTS "Users can update own company measurements" ON public.quality_measurements;
DROP POLICY IF EXISTS "Users can view own company measurements" ON public.quality_measurements;
DROP POLICY IF EXISTS "Users can manage own company reports" ON public.quality_reports;
DROP POLICY IF EXISTS "Users can view own company reports" ON public.quality_reports;
DROP POLICY IF EXISTS quote_items_company_isolation ON public.quote_items;
DROP POLICY IF EXISTS quotes_company_isolation ON public.quotes;
DROP POLICY IF EXISTS "Anyone can view role permissions" ON public.role_permissions;
DROP POLICY IF EXISTS "Users can manage own filters" ON public.saved_filters;
DROP POLICY IF EXISTS "Users can view own filters or company defaults" ON public.saved_filters;
DROP POLICY IF EXISTS "Admins can manage reports" ON public.scheduled_reports;
DROP POLICY IF EXISTS "Users can view company reports" ON public.scheduled_reports;
DROP POLICY IF EXISTS "Admins can manage tags" ON public.tags;
DROP POLICY IF EXISTS "Users can create company tags" ON public.tags;
DROP POLICY IF EXISTS "Users can delete company tags" ON public.tags;
DROP POLICY IF EXISTS "Users can update company tags" ON public.tags;
DROP POLICY IF EXISTS "Users can view company tags" ON public.tags;
DROP POLICY IF EXISTS "Managers can update all company time logs" ON public.time_logs;
DROP POLICY IF EXISTS "Owners and managers can delete time logs" ON public.time_logs;
DROP POLICY IF EXISTS "Users can create time logs" ON public.time_logs;
DROP POLICY IF EXISTS "Users can update their own time logs" ON public.time_logs;
DROP POLICY IF EXISTS "Users can view their company time logs" ON public.time_logs;
DROP POLICY IF EXISTS "Admins can manage user permissions" ON public.user_permissions;
DROP POLICY IF EXISTS "Users can view permissions in their company" ON public.user_permissions;
DROP POLICY IF EXISTS "Manage own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Users can create own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Users can update own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Users can view own preferences" ON public.user_preferences;
DROP POLICY IF EXISTS "Allow trigger to create users" ON public.users;
DROP POLICY IF EXISTS "Only owners can delete users" ON public.users;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.users;
DROP POLICY IF EXISTS "Users can view users in their company" ON public.users;
DROP POLICY IF EXISTS "Users can access their company warehouse document items" ON public.warehouse_document_items;
DROP POLICY IF EXISTS "Users can access their company warehouse documents" ON public.warehouse_documents;
